FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_golang_1.25 AS builder

ARG SOURCE_DIR="/go/src/github.com/openshift/cert-manager-trust-manager"

COPY . $SOURCE_DIR
COPY LICENSE /licenses/

ENV GO_BUILD_TAGS=strictfipsruntime,openssl
ENV GOEXPERIMENT=strictfipsruntime
ENV CGO_ENABLED=1
ENV GOFLAGS=""

RUN cd $SOURCE_DIR/cmd/trust-manager && go build -o $SOURCE_DIR/_output/cert-manager-trust-manager -ldflags '-w -s' -tags ${GO_BUILD_TAGS} main.go

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:ae09ecc3d754bc1726cbda3e2599cc7839e09fe1cc547ce173cf669b645be3cc

ARG RELEASE_VERSION
ARG COMMIT_SHA
ARG SOURCE_URL
ARG SOURCE_DIR="/go/src/github.com/openshift/cert-manager-trust-manager"

COPY --from=builder $SOURCE_DIR/_output/cert-manager-trust-manager /usr/local/bin/cert-manager-trust-manager
COPY --from=builder /licenses /licenses

USER 65534:65534

LABEL com.redhat.component="cert-manager-trust-manager-container" \
      cpe="cpe:/a:redhat:cert_manager:1.19::el9" \
      name="cert-manager/cert-manager-trust-manager-rhel9" \
      version="${RELEASE_VERSION}" \
      summary="cert-manager-trust-manager" \
      maintainer="Red Hat, Inc." \
      description="cert-manager-trust-manager-container" \
      vendor="Red Hat, Inc." \
      release="${RELEASE_VERSION}" \
      io.openshift.expose-services="" \
      io.openshift.tags="data,images,cert-manager-trust-manager" \
      io.openshift.build.commit.id="${COMMIT_SHA}" \
      io.openshift.build.source-location="${SOURCE_URL}" \
      io.openshift.build.commit.url="${SOURCE_URL}/commit/${COMMIT_SHA}" \
      io.k8s.display-name="cert-manager-trust-manager" \
      io.k8s.description="cert-manager-trust-manager-container"

ENTRYPOINT ["/usr/local/bin/cert-manager-trust-manager"]
